# Generated by Django 4.2.2 on 2023-07-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/rooms')),
                ('description', models.TextField(max_length=50, null=True)),
                ('products', models.ManyToManyField(to='homevibe.product')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homevibe.style')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
