# Generated by Django 4.2.2 on 2023-08-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.TextField(choices=[('brown', 'Brown'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink')], default='brown', max_length=30),
        ),
    ]
