# Generated by Django 4.2.2 on 2023-08-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0002_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_option',
        ),
    ]
