# Generated by Django 4.2.2 on 2023-07-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0002_photo_delete_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='homevibe_photo',
        ),
    ]
