# Generated by Django 4.2.2 on 2023-07-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0003_alter_photo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
