# Generated by Django 4.2.2 on 2023-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0004_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
