# Generated by Django 4.2.2 on 2023-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/images/product'),
        ),
    ]
