# Generated by Django 4.2.2 on 2023-08-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0007_rename_category_room_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color',
        ),
    ]
