# Generated by Django 4.2.2 on 2023-08-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0008_rename_name_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
    ]
