# Generated by Django 4.2.2 on 2023-08-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0009_rename_color_color_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color',
        ),
    ]
