# Generated by Django 4.2.2 on 2023-08-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homevibe', '0011_rename_color_color_color_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_option',
        ),
    ]
